### ISSUE TITLE
TypeError: unbound method request()

### ISSUE THREAD

**Issue by jangrewe** [andrey-pohilko/registry-cli#11]
Hi, we're using your script as part of our CI process, but sometimes it fails with an error like the one below and breaks the build process:

```
$ registry-cli -r https://${REGISTRY} --delete --num 5 --keep-tags "qa" --image "${IMAGE}"
Will delete all but 5 last tags
---------------------------------
Image: ptv/frontend-v2
Traceback (most recent call last):
  File "/usr/bin/registry-cli", line 449, in <module>
    main_loop(args)
  File "/usr/bin/registry-cli", line 388, in main_loop
    all_tags_list = registry.list_tags(image_name)
  File "/usr/bin/registry-cli", line 134, in list_tags
    result = self.send("/v2/{0}/tags/list".format(image_name))
  File "/usr/bin/registry-cli", line 112, in send
    verify = not self.no_validate_ssl)
TypeError: unbound method request() must be called with Requests instance as first argument (got str instance instead)
```

It works more often than not, but those one-off errors are a bit annoying ;-)

**Comment by andrey-pohilko** [comment]
Hi,

Let's try to find and fix :) (I hate floating errors :))

Please provide more details:

1. issue a "registry-cli -r https://${REGISTRY} --image "${IMAGE}
--tags" command
at your registry and send me output of tags with this particular image
2. does it always happen with the same image name or different?
3. please provide image names that you face the issue with

Regards,
Andrey

**Comment by jangrewe** [comment]
Right now it seems completely broken, i can't even list anything anymore. (And "--tags" doesn't seem to be a valid argument). Event a simple
```
registry-cli -r https://registry.example.com
```
gives me that error. So i'd say it happens with every image.

The image name is nothing special: `ptv/frontend-v2`

A curl request to `/v2/_catalog` on that host works fine, i get the JSON that shows me all images.

**Comment by jangrewe** [comment]
I just reverted to an older version to test were it stops working, looks like this commit broke it for me: https://github.com/andrey-pohilko/registry-cli/commit/2c632c90862093de7f74f2bcae2e9d4c7c558ccb

**Comment by andrey-pohilko** [comment]
I've found one error with the Registry.send function, please update your version and check how it works now.

**Comment by jangrewe** [comment]
Works like a charm, thanks for your incredibly fast response!
