### ISSUE TITLE
Compatibility fix for Nexus Docker Registry

### ISSUE THREAD

**Issue by reach3r** [andrey-pohilko/registry-cli#14]
While trying to cleanup our Nexus Docker Registry with this cool little tool I stumbled on the fact that in its current Version (3.2.1) HEAD requests are not allowed and result in 404 errors.
To fix this I changed the method to GET ([here](https://github.com/andrey-pohilko/registry-cli/blob/master/registry.py#L151)) which resolved the issue for me.

``` bash
~$ curl -i --head -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' -u foo:bar "https://private.docker.registry/v2/bookmarks/manifests/latest"
HTTP/1.1 404 Not Found
Date: Wed, 29 Mar 2017 08:04:34 GMT
Content-Type: text/html
Content-Length: 1843
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Pragma: no-cache
Cache-Control: post-check=0, pre-check=0
Expires: 0

~$ curl -i --head -X GET -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' -u foo:bar "https://private.docker.registry/v2/bookmarks/manifests/latest"
HTTP/1.1 200 OK
Date: Wed, 29 Mar 2017 08:05:24 GMT
Content-Type: application/vnd.docker.distribution.manifest.v2+json
Content-Length: 4931
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Docker-Distribution-Api-Version: registry/2.0
Last-Modified: Fri, 24 Mar 2017 09:59:15 GMT
Docker-Content-Digest: sha256:49527f070c474597e596c0cadfe0e402d9fd3036ce744d17e4ce43c223ac10f4
```

**Comment by andrey-pohilko** [comment]
Hey, I installed Nexus3 locally, created new repo "Docker (hosted)" on port 5000, enabled the HTTP connector on port 5000, enabled API v1, uploaded an image into it, ran registry.py against it... it worked!

Secondly, why do you think that `curl --head` and `curl --head -X get` are different commands? 
`GET` is the default request method used when no -X flag was specified. Please check your setup again, please and report whether you were able to run the tool.

Thanks

**Comment by reach3r** [comment]
Hey,

according to the curl man page:
> -I/--head
(HTTP/FTP/FILE) Fetch the HTTP-header only! HTTP-servers feature the command HEAD which this uses to get nothing but the header of a document. When used on a FTP or FILE file, curl displays the file size and last modification time only.

Which means that unless `-X GET` is also specified, `--head` will not issue the GET method.

And from my testing not using the GET method will not work with the Nexus Docker Registry.
Since it has been a while I don't remember the specifics off the top of my head, but if I remember correctly I had no or no significant problems using registry.py for reading the registry, but it would not work if I wanted to modify stuff (issue remove commands).
Have you tried deleting the image in your test registry?

Let me know if I can help you with more specifics.
Cheers

**Comment by pjanuario** [comment]
This fork was made for that reason and I was about to do one because of that also. Would be great to see this commit integrated here.

https://github.com/izhangzhihao/nexus-docker-registry-cli/commit/9cfa655041d9e3e301a761b6f9a1c221a7ebd0da

**Comment by andrey-pohilko** [comment]
Since this issue is duplicated and issue #23 has more active discussion, this issue is closed.

Let's make something useful together in #23
