### ISSUE TITLE
If --tags-like doesn't find any matches, all tags will be selected

### ISSUE THREAD

**Issue by davidlar** [andrey-pohilko/registry-cli#15]
Hi!

I bumbed into a problem when using --tags-like. 
When I was running 
`registry.py -r http://localhost:5000 --tags-like "SNAPSHOT" --delete-all` 
and some repos didn't contain any snapshot tags, all tags would be deleted on those repos.
I did a dry-run before the deletion, so no harm done ;-) 

I think the row:
  if len(tags_list) == 0:

should be changed to:
  if len(tags_list) == 0 and not args.tags_like:

Thanks for a great tool!
Regards David

**Comment by andrey-pohilko** [comment]
Thanks for the feedback. Let me check possible solutions and test it.

**Comment by andrey-pohilko** [comment]
Hey, I believe I've fixed the issue. Please download recent version and check (with --dry-run enabled, just in case)

**Comment by andrey-pohilko** [comment]
As per my tests, this issue is fixed. Thus, I'm closing it.
