### ISSUE TITLE
Could you make login optional

### ISSUE THREAD

**Issue by pcm32** [andrey-pohilko/registry-cli#2]
Hi, 

Thanks for this nice utility! Do you think you could make the login optional, we have some internal private repos that we protect through reverse proxies, but that we don't authenticate to them when used from the local network. Currently:

```
$ python registry.py -r 192.168.1.34:5000
usage: registry.py [-h] -l USER:PASSWORD -r URL [-d] [-n [N]] [--dry-run]
                   [-i IMAGE:[TAG] [IMAGE:[TAG] ...]] [--delete-all]
                   [--layers]
registry.py: error: argument -l/--login is required
```

Thanks!

**Comment by andrey-pohilko** [comment]
Hey man, I've made the '-l' flag optional.

Enjoy!

Regards,
Andrey
