### ISSUE TITLE
Does this support Nexus Private registry

### ISSUE THREAD

**Issue by amruthapbhat** [andrey-pohilko/registry-cli#23]
Hi,

I have all the docker images in Nexus Hosted Repo and iam trying to use this script to delete images but its not working and iam getting the below error

Getting digest for tag 11
  tag digest not found: 404
Tag 11 does not exist for image amruthapbhat/customerservices. Ignore here.

Could you please let us know if this supports for Nexus as well?

**Comment by andrey-pohilko** [comment]
Can you provide the link to the Nexus Hosted Repo? I didn't test my script against this registry and cannot say whether it is supported or not.

Are other tags processed ok?

Can you send me full output of your script?

**Comment by amruthapbhat** [comment]
Hi,

It gives the listing of all the images in the repo.

When i try to delete the image it gives the below error
Image: ImageName
  tag: latest
Getting digests for tags to keep:
Getting digest for tag latest
  tag digest not found: 404
Tag latest does not exist for image ImageName. Ignore here.
Getting digest for tag latest
  tag digest not found: 404
Tag latest does not exist for image ImageName. Ignore here.

**Comment by izhangzhihao** [comment]
@amruthapbhat Try this https://github.com/izhangzhihao/nexus-docker-registry-cli

**Comment by pjanuario** [comment]
@andrey-pohilko this commit is required to use with nexus registry.

https://github.com/izhangzhihao/nexus-docker-registry-cli/commit/9cfa655041d9e3e301a761b6f9a1c221a7ebd0da

**Comment by andrey-pohilko** [comment]
I know that. It will need some time to make sure that this change will not affect the original docker registry. If you can run script with ("GET") instead of ("HEAD") against the original registry and run some tests, I (and all users of this script) will be grateful to you

**Comment by kieranshaw** [comment]
I've not been able to test this against another but a Nexus 3 docker registry, but I can confirm that for that scenario, I did indeed have to send the GET request instead of the HEAD to get the digest.

**Comment by andrey-pohilko** [comment]
I added flag `--digest-method GET` to support Nexus

**Comment by nickcaballero** [comment]
Related Nexus issue - https://issues.sonatype.org/browse/NEXUS-12684
