### ISSUE TITLE
failed, error 405

### ISSUE THREAD

**Issue by askz** [andrey-pohilko/registry-cli#27]
Hi, I'm using registry v2 in swarm behind traefik, I got no problems to list all my tags and repos but when I try to delete some, I get 405 error: 

```console
  deleting tag 0.2.1
failed, error: 405
  deleting tag 0.2.3
failed, error: 405
  deleting tag 0.2.4
failed, error: 405
  deleting tag 0.2.5
```

**Comment by andrey-pohilko** [comment]
You need to enable image deletion in your registry configuration (see in the readme how to do it)

**Comment by askz** [comment]
Yup my bad, that was that.

Thanks :)
