### ISSUE TITLE
Garbage collection command should include the --rm flag.

### ISSUE THREAD

**Issue by chris13524** [andrey-pohilko/registry-cli#29]
The command below (from the [README](https://github.com/andrey-pohilko/registry-cli#garbage-collection-in-docker-registry)) will leave `run_x` containers behind:
```
docker-compose run registry bin/registry garbage-collect /etc/docker/registry/config.yml
```
It should be updated to include the `--rm` flag to prevent this:
```
docker-compose run --rm registry bin/registry garbage-collect /etc/docker/registry/config.yml
```

**Comment by andrey-pohilko** [comment]
updated readme, thanks
