### ISSUE TITLE
Images not being deleted?

### ISSUE THREAD

**Issue by chris13524** [andrey-pohilko/registry-cli#30]
Maybe I'm misunderstanding Docker, but it seems like this script isn't actually deleting images. It does tags, but I'm still left with 9 GiB (!) of images.

My goal is I want to `docker push` an image of mine to this registry, and then immediately pull it from another server. This way I should be able to only push the changes I made most recently instead of having to upload the _entire_ image each time via `docker export/import`.

Anyways, I'm running this script and then the garbage collector, but I'm still left with dozens of images. I'd like to get rid of all those old versions.

I was originally doing this:
`docker run --rm --network="coconutstack_default" anoxis/registry-cli -r http://registry:5000 --delete --num=0`
But for testing purposes, I "upgraded" to this:
`docker run --rm --network="coconutstack_default" anoxis/registry-cli -r http://registry:5000 --delete-all`
```
---------------------------------
Image: coconut-api
  no tags!
---------------------------------
Image: coconut-client
  no tags!
---------------------------------
Image: coconut-shortener
  no tags!
```
`docker-compose stop registry`
`docker-compose run --rm registry bin/registry garbage-collect /etc/docker/registry/config.yml`
`docker-compose up -d registry`
```
coconut-api
coconut-api: marking manifest sha256:1498e0aae4a3bdb0ffb3aa5d74316cff456b66f2128e373d45979dc3f9bdb95c 
coconut-api: marking blob sha256:51a6e8d21a3c2632176ea92223609205eb3bc26c56d712bcf47c5ce2295c075a
coconut-api: marking blob sha256:627d84b6655ecc4762f44b235ac3069df582d19c4c58905b7cc313fcaa8dd9ab
coconut-api: marking blob 
..... many more of these ...
coconut-client
coconut-client: marking manifest sha256:0ef194b271043151af553252e2f059b6d627009695c29b6701e49a41bc99ff27 
coconut-client: marking blob sha256:1e9ad8bd0dd7bc66f18c067a43f9f64aa3745ac448bdc31d6c0e9db854ce543e
coconut-client: marking blob sha256:5973cba6eb58ebe7d6e8461da953e753d5b047c8ce34e7b695eea96833c23dec
coconut-client: marking blob 
..... more ....

coconut-shortener
coconut-shortener: marking manifest sha256:0cf9a7f9c0cbc1bbf5f50c027085a8a16ba83d4ae54a27f1dc8e11e84377ebaa 
coconut-shortener: marking blob sha256:267cba20434b45830af6e0245bf436ed84be8aebc535b05b387f7140cdc76004
coconut-shortener: marking blob sha256:627d84b6655ecc4762f44b235ac3069df582d19c4c58905b7cc313fcaa8dd9ab
coconut-shortener: marking blob sha256:63b7b9556cec50af3aed16c00f375ed1969a7511a4a5043af4434e5a9fa2c11c
coconut-shortener: marking blob
......... many more of these .....

209 blobs marked, 0 blobs eligible for deletion
```

**Comment by ipavlushin** [comment]
@chris13524 Could you please show your registry config?

**Comment by chris13524** [comment]
I'm using the default, which is:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

**Comment by ipavlushin** [comment]
Looks like you have the same problem as [here](https://github.com/docker/distribution/issues/2434). Something went wrong with GC.
