### ISSUE TITLE
Support deletion by date

### ISSUE THREAD

**Issue by pjanuario** [andrey-pohilko/registry-cli#36]
The current version of the script deletes images using a natural sorting, this means that if one is using commit id or short commit id as tags the script will not keep the last n images as desirable.

There was no direct way to perform this for the time being, so I did some changes in the script to solve the problem by accessing the tag manifest and using a v1 compatibility history property (that might be deprecated in future) to access the creation date.

This solve my problem, but since I can't afford to change the tests and polish my changes to open a decent PR contribution, I leave here the PR (https://github.com/pjanuario/registry-cli/pull/1) I opened for my own fork in case someone need it or desires to use as baseline/research to open a decent contribution.

I think would be good to have a note in the readme to make clear how deletion tag sorting is done.

**Comment by ipavlushin** [comment]
Hey @pjanuario deleting by image age currently available in script. You can use `--delete-by-hours` arg. So I close the issue.
