### ISSUE TITLE
tags should sort by date asc by default.

### ISSUE THREAD

**Issue by davidqhr** [andrey-pohilko/registry-cli#42]
Currently, the tags are sorted by `natural_keys`. I think it is more reasonable to sort tags by date.

**Comment by josephmc5** [comment]
During my testing I found that my currently used tag would have been deleted because of this. I don't think the current sorting method is safe or implicit.

**Comment by andrey-pohilko** [comment]
Please provide details of your testing

pá 18. 1. 2019 6:31 odesílatel Joe McWilliams <notifications@github.com>
napsal:

**Comment by heamaral** [comment]
I have commit hashes on tags of my images. Ex.:
f6464247db2fb81a3148af2e3bdb285ebd48fb15
e8bc5ae108c5b44a02ea00ff912cb9998dada2be
e42eb369fe89c1df0363129f09be13f7bf3ac3aa
e3d9c13a5a10d3226af2f6d0d5ae43bc0d2adfaf
e08527a9da59ffcc8b6386d70bbc5a268f86dc4e
dd1046f1a40994bb75369c9424de480a21fad794
d739166c4e91106616860a4e2654413d55b58dfd
d6fa565a79c885d4df41508e8e0dda0fbe8f3106
d340b2ed9b570162267e501eac9cf14ff0bdf9e6
c34716b304529d5189e84064a74308615d97a963

I did a new commit and build a new Docker image with the following tag:
a9be215680448303d5b6e32589d0e79fb126c355

Then if I run the --delete, the "a9be215680448303d5b6e32589d0e79fb126c355" is deleted.

It doesn't make any sense this kind of sort to removing last tags. It just doesn't work.

**Comment by heamaral** [comment]
I've created a pull request to fix this issue:
#63

**Comment by ipavlushin** [comment]
New filter was added in #73
