### ISSUE TITLE
Registry interaction fails without authentication

### ISSUE THREAD

**Issue by jketterl** [andrey-pohilko/registry-cli#47]
In a recent change, the registry authentication mechanism now always tries to build a login parameter from username and password, even when neither of them, nor the read_password flag has been set, which leads to the following error:

```
Traceback (most recent call last):
  File "/registry.py", line 705, in <module>
    main_loop(args)
  File "/registry.py", line 630, in main_loop
    args.login = username + ':' + password
UnboundLocalError: local variable 'username' referenced before assignment
```

The change in question is [here](https://github.com/andrey-pohilko/registry-cli/commit/8e6fc93d4e2e2d3c66674961ace4e2b09e1d70c9).

**Comment by andrey-pohilko** [comment]
yes, such a dump mistake of me

will change the code to cover this by tests also

**Comment by jketterl** [comment]
no problem :) it is working again now. thanks for fixing it :)
