### ISSUE TITLE
Please provide docker-container automated build on docker hub

### ISSUE THREAD

**Issue by Hubbitus** [andrey-pohilko/registry-cli#6]
To do not manually clone it on each servers where it used and do not introduce additional environment dependencies like git and python.

It will be cool see it in thin alpine base image.

**Comment by andrey-pohilko** [comment]
Please tell me more about your setup. In particular, I want to understand, why you need to copy it to each server, since registry.py connects to docker-registry remotely.

**Comment by Hubbitus** [comment]
My intention run it from just one docker command without setup any environment like python. So I have docker registry - it will be very convenient run you script also in container to deal with cleanup.

**Comment by Hubbitus** [comment]
Do you willing I made PR with Dockerfile?
