### ISSUE TITLE
Any particular reason for a strict GNU GPL v3 license and not MIT?

### ISSUE THREAD

**Issue by spk83** [andrey-pohilko/registry-cli#60]
Would you consider changing license to MIT from GNU GPL v3? GNU GPL v3 requires to make all source code public where this script might be used in some shape or form which is really difficult to do when working in a organization behind firewall...

**Comment by andrey-pohilko** [comment]
The GNU GPL v3 requires you to open source your code only if you distribute it. If you intend to use it for internal purpose, you are free to change it with no limitations and integrate it into your proprietary systems.
