### ISSUE TITLE
Pushing a previous deleted image causes errors

### ISSUE THREAD

**Issue by gfenn-newbury** [andrey-pohilko/registry-cli#62]
While testing this with a private registry, I have found a couple of potential bugs. The workflow goes as follows:

```
docker pull ubuntu:18.04
...
docker tag ubuntu:18.04 172.17.0.2:5000/ubuntu:18.04
docker push 172.17.0.2:5000/ubuntu:18.04
The push refers to repository [172.17.0.2:5000/ubuntu]
2c77720cf318: Pushed 
1f6b6c7dc482: Pushed 
c8dbbe73b68c: Pushed 
2fb7bfc6145d: Pushed 
18.04: digest: sha256:cef0c2cde57a973ed80513a7d3614bc654d9d6becad2c068c9328b41bb3f6713 size: 1150
```
(note the _Pushed_ status for the layers)
The above all works as expected. While monitoring with `http://172.17.0.2:5000/v2/ubuntu/tags/list`, you can observe tag `18.04` be created (along with the ubuntu repository). We can even pull the image when it exists to check everything is ok, and as expected, the following happens:
```
docker pull 172.17.0.2:5000/ubuntu:18.04
18.04: Pulling from ubuntu
Digest: sha256:cef0c2cde57a973ed80513a7d3614bc654d9d6becad2c068c9328b41bb3f6713
Status: Image is up to date for 172.17.0.2:5000/ubuntu:18.04
```
When deleting with `docker run -d anoxis/registry-cli -r http://172.17.0.2:5000 --delete-all` followed with `docker exec ddfbb6fb4338 /bin/registry garbage-collect /etc/docker/registry/config.yml`, everything works fine. When observing the output of `http://172.17.0.2:5000/v2/ubuntu/tags/list`, you can see the ubuntu repository only has `null` as a tag, as expected.

However, if you try and push `ubuntu:18.04` again, the following happens:
```
docker push 172.17.0.2:5000/ubuntu:18.04
The push refers to repository [172.17.0.2:5000/ubuntu]
2c77720cf318: Layer already exists 
1f6b6c7dc482: Layer already exists 
c8dbbe73b68c: Layer already exists 
2fb7bfc6145d: Layer already exists 
18.04: digest: sha256:cef0c2cde57a973ed80513a7d3614bc654d9d6becad2c068c9328b41bb3f6713 size: 1150

docker pull 172.17.0.2:5000/ubuntu:18.04
Error response from daemon: manifest for 172.17.0.2:5000/ubuntu:18.04 not found
```
Again, `http://172.17.0.2:5000/v2/ubuntu/tags/list` shows the `18.04` tag in the `ubuntu` repository, but obviously something hasn't worked here.

**Edit**
This is the output of the log when trying to delete the borked `18.04`:
```
docker logs 0770585a2691
---------------------------------
Image: ubuntu
  tag: 18.04
  deleting tag 18.04
  tag digest not found: 404.
Try adding flag --digest-method=GET
```
I did try using `--digest-method=GET`, and the response is the same

**Comment by ipavlushin** [comment]
This is not `registry-cli` related issue. It is docker registry [issue](https://github.com/docker/distribution/issues/1803)

**Comment by ipavlushin** [comment]
@GNewbury1 Try to restart docker registry after garbage collect. And push it again.
