### ISSUE TITLE
No need to stop and restart registry for garbage-collect

### ISSUE THREAD

**Issue by glarivie** [andrey-pohilko/registry-cli#65]
I suggest to edit the notes about garbage-collect, there is not need to stop and restart the container or even to create a new one.

```
docker exec -it registry /bin/ash -c "/bin/registry garbage-collect /etc/docker/registry/config.yml"
```

**Comment by ipavlushin** [comment]
It actually required if you want to be safe with your images.

> Note: You should ensure that the registry is in read-only mode or not running at all. If you were to upload an image while garbage collection is running, there is the risk that the image’s layers are mistakenly deleted leading to a corrupted image.
https://docs.docker.com/registry/garbage-collection/#more-details-about-garbage-collection
