### ISSUE TITLE
Docker hub image outdated

### ISSUE THREAD

**Issue by olfway** [andrey-pohilko/registry-cli#78]
Please, update docker hub image.
It was built 4 months ago and doesn't support --order-by-date option

**Comment by Constantin07** [comment]
Having the same issue. Any plans to update the docker image ?

**Comment by ipavlushin** [comment]
Thanks for noticing it, will update soon.

**Comment by andrey-pohilko** [comment]
this has been resolved.

we are also now setting up a separate docker hub repo and will publish the changes once it has been established

**Comment by Constantin07** [comment]
Thanks @andrey-pohilko
