### ISSUE TITLE
TypeError with --dry-run --delete

### ISSUE THREAD

**Issue by thomasme** [andrey-pohilko/registry-cli#8]
Hi, thanks for this great tool! I can list repositories and tags from our private repository. However, when I try to --delete (with --dry-run) the following error pops up:

	thomas@dockerhost:~$ registry.py -r http://docker.example.com --tags-like jenkins --dry-run --delete
	Will delete all but 10 last tags
	---------------------------------
	Image: myapp
	tag like: jenkins
	Adding jenkins-myapp-build-docker-257 to tags list
	  tag: jenkins-myapp-build-docker-257
	Traceback (most recent call last):
	  File "/registry.py", line 413, in <module>
	    main_loop(args)
	  File "/registry.py", line 404, in main_loop
	    tags_list_to_delete = tags_list[:-keep_last_versions]
	TypeError: 'set' object has no attribute '__getitem__'

The same thing happens without --tags-like. I did not try without --dry-run, but I guess it wouldn't make a difference. Googling the error, I found "Your config dictionary has a typo somewhere in it that causes it to be created as a set, rather than a dictionary", but I'm not a python wizard, probably you can tell immediately what the problem is.

**Comment by jangrewe** [comment]
Same here, definitely also occuring without `--dry-run`, just providing the registry url with `-r` and deleting with `-d`

**Comment by magicalbob** [comment]
I've fixed this issue on my own copy. tags_list is a set object. Needs casting as a list:

```
diff --git a/registry.py b/registry.py
index 8821c1a..3c9c04c 100755
--- a/registry.py
+++ b/registry.py
@@ -399,9 +399,9 @@ def main_loop(args):
         # delete tags if told so
         if args.delete or args.delete_all:
             if args.delete_all:
-                tags_list_to_delete = tags_list
+                tags_list_to_delete = list(tags_list)
             else:
-                tags_list_to_delete = tags_list[:-keep_last_versions]
+                tags_list_to_delete = list(tags_list)[:-keep_last_versions]
 
             delete_tags(
                 registry, image_name, args.dry_run,
```

**Comment by andrey-pohilko** [comment]
Thank you.
Will fix it as @magicalbob suggested and commit.

**Comment by jangrewe** [comment]
Works like a charm, thanks @magicalbob and @andrey-pohilko
