### ISSUE TITLE
How can I delete un-tagged images?

### ISSUE THREAD

**Issue by aalemanq** [andrey-pohilko/registry-cli#99]
I'm running this cleaner every week with next command:

```
/registry.py -r https://registry --delete --order-by-date --no-validate-ssl --num 30 --dry-run
```

But after a few months , I realise that un-tagged images are not deleted.

```
2021-03-05 07:49:33,738 INFO >> Total images size: 612.67 GB                                             
2021-03-05 07:49:33,738 INFO >> Tagged images size: 181.53 GB             
2021-03-05 07:49:33,738 INFO >> Un-tagged images size: 453.48 GB
output from https://pypi.org/project/docker-registry-statistics/
```

So my registry is full and after run garbage collector, still the same, just delete tagged images :(

**Comment by aalemanq** [comment]
I discovered that apply this:

bin/registry garbage-collect --delete-untagged /etc/docker/registry/config.yml is working :D

SOLVED!

**Comment by andrey-pohilko** [comment]
thanks, that's an important note
